version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  question_answering_app:
    image: frankkyei/docker-question_answering_app:latest
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=elasticsearch
    ports:
      - 5000:5000
